[topology]
name = "Test sleep"

[[node]]
name = "sleep_node"
host = "127.0.0.1"
agent_port = 7700 
services = ["sleep", "logging"]
deploy_user = "mike"
deploy_path = "/home/mike/projects/icpc-live-infra-rs/deploy"

[[service]]
name = "sleep"
command = "sleep"
args = ["3"]
restart = "always"
depends_on = [{ service = "logging", node = "sleep_node"}]

[[service]]
name = "logging"
command = "python3"
args = ["examples/main.py"]
restart = "always"
healthcheck = { http = "http://localhost:8080", interval_ms = 5000, timeout_ms = 2000 }

[service.deploy]
files = [
  "examples/main.py"
]
